/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 tree.glb -T -i -k 
Files: tree.glb [7.08KB] > /Users/krissorensen/Software Engineering/Website Intros/Zurchers/zurchers-next/public/models./models/tree-transformed.glb [3.06KB] (57%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function TreeModel(props) {
  const { nodes, materials } = useGLTF("./models/tree-transformed.glb");
  return (
    <group {...props} dispose={null}>
      {/* <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0, -1.026, 0]}
        scale={15}
      /> */}
      <mesh
        name="Cone002"
        geometry={nodes.Cone002.geometry}
        material={materials["Material.001"]}
        position={[0, 5.297, 0]}
        scale={0.969}
      />
      <mesh
        name="Cylinder"
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.002"]}
        scale={[0.63, 1, 0.63]}
      />
    </group>
  );
}

useGLTF.preload("./models/tree-transformed.glb");
